- name: Playbook
  hosts: all
  collections:
    - community.docker
  tasks:
    - name: Start service docker, if not
      ansible.builtin.service:
        name: docker
        state: started    
    - name: Pull fluentd
      community.docker.docker_image_pull:
        name: fluentd        
        platform: amd64
        tag: v1.17-1
        timeout: 60
        pull: not_present
    - name: Copy conf file
      ansible.builtin.copy:
        src: ./fluentd-file/fluentd.conf
        dest: /root/fluentd.conf
        owner: root
        group: root
        mode: '0644'        
    - name: Start fluentd
      community.docker.docker_container:
        name: fluentd-ansible
        image: fluentd:v1.17-1      
        state: started
        ports:
          - 24224:24224
        volumes:
          - /root/fluentd.conf:/fluentd/etc/fluentd.conf